/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.BuyDropPointServiceController;
import domain.DropPoint;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import persistence.OracleDb;
import ui.Main;

/**
 *
 * @author Afonso
 */
public class InterfaceUtilizadorGUI extends javax.swing.JFrame {

    private BuyDropPointServiceController controller;
    private JFrame parentFrame;
    private DropPoint dropChoosed;
    private int idTamanho;
    private int idTemperatura;

    /**
     * Creates new form InterfaceUtilizadorGUI
     */
    public InterfaceUtilizadorGUI(JFrame parent, DropPoint dp, int tamanho, int temperatura) throws SQLException {
        super("User Information");
        parentFrame = parent;
        dropChoosed = dp;
        idTamanho = tamanho;
        idTemperatura = temperatura;
        controller = new BuyDropPointServiceController(Main.CREDENTIALS_FILE);
        initComponents();
        fecharJanela();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeLBL = new javax.swing.JLabel();
        comprarBTN = new javax.swing.JButton();
        sairBTN = new javax.swing.JButton();
        passwordLBL = new javax.swing.JLabel();
        nomeTXT = new javax.swing.JTextField();
        passwordTXT = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Dados Utilizador");

        nomeLBL.setText("Nome:");

        comprarBTN.setText("Comprar");
        comprarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBTNActionPerformed(evt);
            }
        });

        sairBTN.setText("Sair");
        sairBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBTNActionPerformed(evt);
            }
        });

        passwordLBL.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeTXT)
                            .addComponent(passwordTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(comprarBTN)
                        .addGap(73, 73, 73)
                        .addComponent(sairBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLBL)
                    .addComponent(passwordTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprarBTN)
                    .addComponent(sairBTN))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBTNActionPerformed
        if (nomeTXT != null && passwordTXT != null) {
            boolean login = controller.clientLogin(nomeTXT.getText(), passwordTXT.getText());
            if (login) {
                controller.selectDropPoint(dropChoosed.getId());
                controller.selectPreferredDimensions(idTamanho);
                controller.selectPreferredTemperature(idTemperatura);
                boolean idToken = controller.confirmRegister(); 
                if(idToken){
                    this.dispose();
                    String tokenEstafeta=controller.tokenClient();
                    JOptionPane.showMessageDialog(this, "Dados da Reserva\nDropPoint: "+dropChoosed.getNome()+"\nToken: "+tokenEstafeta, "Reserva efetuada com sucesso!", JOptionPane.INFORMATION_MESSAGE, null);
                }
                
            }
        }
    }//GEN-LAST:event_comprarBTNActionPerformed

    private void sairBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBTNActionPerformed
        sair();
    }//GEN-LAST:event_sairBTNActionPerformed
    private void fecharJanela() {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                sair();
            }
        });
    }

    private void sair() {
        String[] options = new String[2];
        options[0] = "Sim";
        options[1] = "Não";
        int op = JOptionPane.showOptionDialog(this, "Deseja cancelar a compra de DropPoint?", "Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (op == 0) {
            dispose();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprarBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeLBL;
    private javax.swing.JTextField nomeTXT;
    private javax.swing.JLabel passwordLBL;
    private javax.swing.JPasswordField passwordTXT;
    private javax.swing.JButton sairBTN;
    // End of variables declaration//GEN-END:variables

}
